ourintell/subscriptions/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

class CreateSubscriptionForm(FlaskForm):
    ticketing_method = SelectField('TicketingMethod',
                           validators=[DataRequired(), Length(min=2, max=20)])
    ticketing_address = StringField('Address',
                           validators=[DataRequired(),])
    tracked_resource_type = SelectField('ResourceType',
                        validators=[DataRequired(),])
    tracked_resource = StringField('TrackResource', validators=[DataRequired()])
    submit = SubmitField('Submit')

ourintell/intell/routes.py
from flask import send_file,request, Blueprint, jsonify, render_template, url_for
import requests

import io
import csv

from  flask import current_app
from ourintell.models import RecordedEvent
from ourintell import db
from sqlalchemy import exc
from  ourintell.intell.utils import ticket_handler

import json 
from hashlib import sha256

intell = Blueprint('intell',__name__)

# This route is used for adding new events
@intell.route("/events", methods = ["POST"])
def add_event():

    event = json.dumps(request.get_json())
    hashedEvent = sha256(event.encode('utf-8')).hexdigest()
    newEventEntry = RecordedEvent(id=hashedEvent,event_data=event)
    
    db.session.add(newEventEntry)

    try:
        db.session.commit()
    except exc.IntegrityError as error:
        error_code = error.orig.args[0]
        if(error_code == 1062):
            return "value already exists", 409
        else:
            return 250

    # Check for subscriptions maching this event
    ticket_handler(newEventEntry)
    return 'Success', 201

@intell.route('/event/<eventId>', methods = ["GET"])
def get_event(eventId):

    event = RecordedEvent.query.filter_by(id = eventId).first()
    event = json.loads(event.event_data)
    return render_template("event.html",event = event)


@intell.route("/", methods = ["GET"])
@intell.route("/events", methods = ["GET"])
def get_events():
    pageSize = 11

    # Create a mutable dict containing the tags
    tags =  request.args.copy()

    # Pop the page argument
    page_string = tags.pop('page', 1)

    filteredEvents = RecordedEvent.get_filtered_events(tags)

    if(page_string == 'last'):
        page_string = len(filteredEvents)//pageSize
    if(page_string == 'first' ):
        page_string = 0
    
    page = int(page_string) - 1
    if page < 0:
        page = 0

    return render_template('events.html', events = filteredEvents[pageSize*page: pageSize*page+pageSize], tags = tags, current_page = page)

@intell.route("/download/events", methods = ["GET"])
def get_events_as_file():
    tags =  request.args.copy()
    if 'page' in tags:
        tags.pop('page')
    filteredEvents_raw = RecordedEvent.get_filtered_events(tags)
    filteredEvents = json.dumps([event['event_data'] for event in filteredEvents_raw])

    string_file = io.StringIO(filteredEvents)
    
    # Creating a bite object
    byte_file = io.BytesIO()
    byte_file.write(string_file.getvalue().encode())
    # Put the file pointer at 0
    byte_file.seek(0)
    string_file.close()

    # Return the created file
    return send_file(
        byte_file,
        as_attachment=True,
        attachment_filename='data.txt',
        mimetype='text/csv'
    )

@intell.route("/download/ip/events", methods = ["GET"])
def get_events_ip_as_file():
    tags =  request.args.copy()
    if 'page' in tags:
        tags.pop('page')
    filteredEvents_raw = RecordedEvent.get_filtered_events(tags)
    filteredEvents_ips = [event['event_data']['source.ip'] for event in filteredEvents_raw if 'source.ip' in event['event_data']]
    filteredEvents = json.dumps(filteredEvents_ips)

    string_file = io.StringIO(filteredEvents)
    
    # Creating a bite object
    byte_file = io.BytesIO()
    byte_file.write(string_file.getvalue().encode())
    # Puts the file pointer at 0
    byte_file.seek(0)
    string_file.close()

    # Return the created file
    return send_file(
        byte_file,
        as_attachment=True,
        attachment_filename='data.txt',
        mimetype='text/csv'
    )

@intell.route("/test", methods = ["GET"])
def test():
    return 'true'

@intell.route('/test_send', methods = ['GET'])
def test_send():
    test = requests.get('http://127.0.0.1:5000/test')
    return jsonify(test.text)

ourintell/subscriptions/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_required, current_user

from ourintell import db
from ourintell.models import Subscription, TicketingMethod, TrackableResourceType
from ourintell.subscriptions.forms import CreateSubscriptionForm
from ourintell.subscriptions.utils import send_verification_email


subscriptions = Blueprint('subscriptions', __name__)


@subscriptions.route("/subscriptions", methods = ["GET","POST"])
@login_required
def get_subscriptions():
    user_subscriptions = current_user.subscriptions
    return render_template("subscriptions.html", title='Subscriptions', subscriptions=user_subscriptions)


@subscriptions.route("/create_subscription", methods = ["GET","POST"])
@login_required
def create_subscription():

    # Get all available ticketing methods and resource types
    methods = [method.method  for method in TicketingMethod.query.all()]
    types = [resource.resource_type for resource in TrackableResourceType.query.all()]

    # Generate the form
    form = CreateSubscriptionForm()
    form.ticketing_method.choices = methods
    form.tracked_resource_type.choices = types

    # Create a db entry with the new subscription
    if form.validate_on_submit():
        user = current_user
        subscription = Subscription(userId = current_user.id,
                                     tracked_resource = form.tracked_resource.data, 
                                     tracked_resource_type = form.tracked_resource_type.data, 
                                     ticketing_method = form.ticketing_method.data, 
                                     ticketing_address = form.ticketing_address.data, 
                                     is_verified = False)
        db.session.add(subscription)
        db.session.commit()
        flash('New subscription added','success' )
        send_verification_email(subscription)
        redirect(url_for('subscriptions.get_subscriptions'))
        return redirect(url_for('subscriptions.get_subscriptions'))

    return render_template("create_subscription.html", title='New Subscription', form=form)

@subscriptions.route("/verify_subscription/<token>", methods = ["GET"])
def verify_subscription(token):
    subscription = Subscription.verify_token(token)
    if(token == None):
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('subscriptions.get_subscriptions'))
    subscription.is_verified = True
    db.session.commit()
    flash('The subscription has been verified', 'success')
    return redirect(url_for('subscriptions.get_subscriptions'))

ourintell/tickets/routes.py
from flask import Blueprint, render_template, url_for, redirect, flash
from flask_login import login_required, current_user
import json

tickets = Blueprint('tickets',__name__)


@tickets.route('/tickets', methods = ["GET"])
@login_required
def get_tickets():
    user_subscriptions = current_user.subscriptions
    user_tickets =[subscription.sent_tickets for subscription in user_subscriptions]
    # Flatten the list
    user_tickets = [item for sublist in user_tickets
                    for item in sublist]

    
    return render_template('notifications.html', tickets = user_tickets)

ourintell/user/routes.py
from flask import request, Blueprint, jsonify, render_template, url_for, flash, redirect, current_app
from flask_login import current_user, login_user, logout_user


from ourintell import db,  bcrypt
from ourintell.user.forms import LoginForm, RegistrationForm , RequestResetForm, ResetPasswordForm
from ourintell.models import User
from ourintell.user.utils import send_reset_email, send_accaunt_verification_email


from sqlalchemy import exc

import json 
from hashlib import sha256

user = Blueprint('user',__name__)

@user.route("/register", methods = ["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('intell.get_events'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, is_verified = False)
        db.session.add(user)
        db.session.commit()

        send_accaunt_verification_email(user)
        flash(f'A verification email has been sent to {form.email.data}', 'success')
        return redirect(url_for('user.login'))
    return render_template("register.html", form = form)

@user.route("/verify_account/<token>", methods = ["GET"])
def verify_account(token):
    user = User.verify_token(token)
    if(token == None):
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('intell.get_events'))
    user.is_verified = True
    db.session.commit()
    flash('Your account has been verified', 'success')
    return redirect(url_for('intell.get_events'))

@user.route("/login", methods = ["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('intell.get_events'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        # Check user credentials
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('intell.get_events'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template("login.html", form = form)


@user.route("/logout", methods = ['GET'])
def logout():
    logout_user()
    return redirect(url_for('intell.get_events'))


@user.route("/reset_password", methods = ["GET", "POST"])
def reset_password_request():
    if current_user.is_authenticated:
        return redirect(url_for('intell.get_events'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to change your password', 'success')
        return redirect(url_for('user.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)

@user.route("/reset_password/<token>", methods = ["GET", "POST"])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('intell.get_events'))
    user = User.verify_token(token)
    if(not user):
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('reset_request'))
    form = ResetPasswordForm()

    # Set new user password
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated!', 'success')
        return redirect(url_for('user.login'))

    return render_template('reset_password.html', title='Reset Password', form=form)

ourintell/templates/create_subscription.html
{% extends "layout.html" %}
{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create subscription</legend>
            <div class="form-group">
                {{ form.ticketing_method.label(class="form-control-label") }}
                {% if form.ticketing_method.errors %}
                    {{ form.ticketing_method(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.ticketing_method.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.ticketing_method(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.ticketing_address.label(class="form-control-label") }}
                {% if form.ticketing_address.errors %}
                    {{ form.ticketing_address(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.ticketing_address.errors %}
                            <span>{{    error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.ticketing_address(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.tracked_resource.label(class="form-control-label") }}
                {% if form.tracked_resource.errors %}
                    {{ form.tracked_resource(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tracked_resource.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.tracked_resource(class="form-control form-control-lg") }}
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.tracked_resource_type.label(class="form-control-label") }}
                {% if form.tracked_resource_type.errors %}
                    {{ form.tracked_resource_type(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.tracked_resource_type.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.tracked_resource_type(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

{% endblock content%}

ourintell/templates/event.html
{% extends "layout.html" %}
{% block content %}

    {% if event["source.ip"] %}
    <h1><a class="event-ip">{{ event["source.ip"] }}</a></h1>
    {% else %}
    <h1><a class="event-ip">{{ event["source.network"] }}</a></h1>
    {% endif %}
    <table class="table mt-10">
      {% for field in event %}
        <tr>
          <td>{{field}}</th>
          <td>{{event[field]}}</td>
        </tr>
      {% endfor %}
    </table>


    {% for scan in scan_results %}
    <button data-toggle="collapse" data-target="#demo3">Nmap scan</button>

    <div id="demo3" class="collapse border">
      <p>
      {{ scan }}
      </p>
    </div>


    {% endfor %}

     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% endblock content %}

ourintell/templates/events.html
{% extends "layout.html" %}
{% block content %}

<div class="input-group mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">tags:</span>
  </div>
  <input type="text" id="search_box" class="form-control" placeholder="tag1,tag2,tag3" aria-label="tags" aria-describedby="basic-addon1">
</div>


  <div class="d-flex justify-content-end">
    <a id="download-btn" class = "p-sm-1" href="{{ url_for('intell.get_events_as_file')}}" download>
      <button type="button" class="btn btn-secondary">Download</button>
    </a>
    <a id="download-ip-btn" class = "p-sm-1" href="{{ url_for('intell.get_events_ip_as_file')}}" download>
      <button type="button" class="btn btn-secondary">Download IPs</button>
    </a>
  </div>
  {% for event in events %}
      <article class="media content-section">
        <div class="media-body">
          {% if event['event_data']["source.ip"] %}
          <h2><a class="event-ip" href="{{ url_for('intell.get_event', eventId = event['id']) }}">{{ event['event_data']['source.ip'] }}</a></h2>
          {% elif event['event_data']["source.network"] %}
          <h2><a class="event-ip" href="{{ url_for('intell.get_event', eventId = event['id']) }}">{{ event['event_data']['source.network'] }}</a></h2>
          {%else%}
          <h2><a class="event-ip" href="{{ url_for('intell.get_event', eventId = event['id']) }}"> {{ event['event_data']['source.fqdn'] }} </a></h2>
          {% endif %}
          <p class="article-content">{{ event['event_data']["feed.provider"] }}</p>
        </div>
      </article>
  {% endfor %}


  {% set last,first = "last","first" %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <li class="page-item">
        <a class="page-link" href="{{ url_for('intell.get_events', page=first,**tags)}}" tabindex="-1">&lt&lt</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{{ url_for('intell.get_events', page=current_page ,**tags)}}" tabindex="-1">&lt</a>
      </li>

      <li class="page-item"><a class="page-link" href="#">{{current_page + 1}}</a></li>


      
      <li class="page-item">
        <a class="page-link" href="{{ url_for('intell.get_events', page= current_page + 2,**tags)}}">&gt</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="{{ url_for('intell.get_events', page='last',**tags)}}">&gt&gt</a>
      </li>
    </ul>
  </nav>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script type="text/javascript" src="{{ url_for('static', filename='events.js') }}"></script>
{% endblock content %}

ourintell/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>OurIntell - {{ title }}</title>
    {% else %}
        <title>OurIntell</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">OurIntell</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{url_for('intell.get_events')}}">Events</a>
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{url_for('subscriptions.get_subscriptions')}}">Subscriptions</a>
              <a class="nav-item nav-link" href="{{ url_for('tickets.get_tickets') }}">Notifications</a>
              {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav align-items-center">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link " href="{{ url_for('user.logout') }}">Logout</a>
              <h3 class = "nav-item navbar-text ml-2"> {{current_user.username}}</h3>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('user.register') }}">Register</a>
              {% endif%}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


</body>
</html>

ourintell/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('user.reset_password_request') }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('user.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

ourintell/templates/notifications.html
{% extends "layout.html" %}
{% block content %}

{% if current_user.is_verified %}
  {% for ticket in tickets %}

    <article class="row content-section">
      <div class = 'col'>
        <h3><em class="text-muted h3 small">SubscriptionID:</em> {{ ticket.subscriptionId}}</h3>
      </div>
      <div class="col d-inline-block text-truncate "  >
        <h3><em class="text-muted h3 small">EventID:</em> {{ ticket.eventId }}</h3>
    </article>
  {% endfor %}
{% else %}
  <div class="alert alert-danger">
    You need to verify your account to make subscriptions!
  </div>
{% endif %}
{% endblock content%}

ourintell/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('user.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

ourintell/templates/request_reset.htm
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

ourintell/templates/subscriptions.html
{% extends "layout.html" %}
{% block content %}

{% if current_user.is_verified %}
  <article class="conteiner content-section justify-content-center " >
    <a   href="{{ url_for('subscriptions.create_subscription') }}">
      Create subscription
  </a>
  </article>

  {% for subscription in subscriptions %}

    <article class="row content-section">
      {% if not subscription.is_verified %}
        <div class="alert alert-danger">
            Not is_verified.
        </div>
      {% else %}
        <div class="justify-content-center d-flex align-items-center">
          <h3><em class="text-muted h3 small">Id:</em> {{ subscription.id }}</h3>
        </div>
      {% endif %}

      <div class = 'col'>
        <h3><em class="text-muted h3 small">Type:</em> {{ subscription.tracked_resource_type }}</h3>

        <h3><em class="text-muted h3 small">Tracking:</em> {{ subscription.tracked_resource }}</h3>
      </div>
      <div class="col d-inline-block text-truncate "  >
        <h3><em class="text-muted h3 small">Method:</em> {{ subscription.ticketing_method }}</h3>
        <h3><em class="text-muted h3 small text-truncate">Address:</em> {{ subscription.ticketing_address }}</h3>
    </article>
  {% endfor %}
{% else %}
  <div class="alert alert-danger">
    You need to verify your account to make subscriptions!
  </div>
{% endif %}
{% endblock content%}